# Generated by Django 4.2 on 2023-06-13 23:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rod_type', models.CharField(choices=[('', 'Избери тип'), ('Мач', 'Мач'), ('Телемач', 'Телемач'), ('Телескоп', 'Телескоп'), ('Спининг', 'Спининг'), ('Друг', 'Друг')], max_length=12, verbose_name='Тип')),
                ('length', models.FloatField(validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(14)], verbose_name='Дължина')),
                ('guides', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(14)], verbose_name='Брой Водачи')),
                ('rod_name', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Име на модел')),
                ('action', models.CharField(choices=[('', 'Избери акция'), ('1-5', '1-5'), ('1-8', '1-8'), ('5-12', '5-12'), ('10-27', '10-27'), ('20-40', '20-40'), ('10-50', '10-50'), ('40-80', '40-80'), ('Друг', 'Друг')], max_length=10, verbose_name='Акция')),
                ('color', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Цвят')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(2500)], verbose_name='Цена')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Снимка URL')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
