# Generated by Django 4.2 on 2023-05-15 10:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('', 'Избери тип'), ('За сафрид', 'За сафрид'), ('За чернокоп', 'За чернокоп'), ('За карагьоз', 'За карагьоз'), ('За паламуд', 'За паламуд'), ('Друг', 'Друг')], verbose_name='Тип')),
                ('number_of_hooks', models.CharField(choices=[('', 'Брой куки'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('Друг', 'Друг')], verbose_name='Брой куки')),
                ('hook_number', models.CharField(choices=[('', 'Брой куки'), ('10', '10'), ('12', '12'), ('14', '14'), ('16', '16'), ('18', '18'), ('20', '20'), ('Друг', 'Друг')], verbose_name='Номер кука')),
                ('main_line_thickness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.2, message='Основната линия не може да бъде по-тънка от 0.2'), django.core.validators.MaxValueValidator(0.6, message='Основната линия не може да бъде по-дебела от 0.6')], verbose_name='Майка')),
                ('semi_main_line_thickness', models.FloatField(validators=[django.core.validators.MinValueValidator(0.16, message='Бидема не може да бъде по-тънък от 0.16'), django.core.validators.MaxValueValidator(models.FloatField(validators=[django.core.validators.MinValueValidator(0.2, message='Основната линия не може да бъде по-тънка от 0.2'), django.core.validators.MaxValueValidator(0.6, message='Основната линия не може да бъде по-дебела от 0.6')], verbose_name='Майка'), message='Бидема не може да бъде по-дебел от основната линия')], verbose_name='Бидем')),
                ('color', models.CharField(choices=[('', 'Цвят'), ('Черга', 'Черга'), ('Зелено', 'Зелено'), ('Жълто', 'Жълто'), ('Синьо', 'Синьо'), ('Червено', 'Червено'), ('Тиква', 'Тиква'), ('Друг', 'Друг')], verbose_name='Цвят')),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(4, message='Няма толкова евтино чепаре с цена под 4 лв.'), django.core.validators.MaxValueValidator(20, message='Няма толкова скъпо чепаре с цена над 20 лв.')], verbose_name='Цена')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Снимка URL')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
