# Generated by Django 4.2 on 2023-06-13 23:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('', 'Избери размер'), ('1000', '1000'), ('2000', '2000'), ('3000', '3000'), ('4000', '4000'), ('5000', '5000'), ('6000', '6000'), ('7000', '7000'), ('8000', '8000'), ('Друг', 'Друг')], verbose_name='Размер')),
                ('gear_ratio', models.CharField(choices=[('', 'Пред.число'), ('4.2:1', '4.2:1'), ('4.9:1', '4.9:1'), ('5:1', '5:1'), ('5.2:1', '5.2:1'), ('5.3:1', '5.3:1'), ('5.4:1', '5.4:1'), ('5.7:1', '5.7:1'), ('6.1:1', '6.1:1'), ('6.2:1', '6.2:1'), ('6.5:1', '6.5:1'), ('Друг', 'Друг')], verbose_name='Пред.число')),
                ('model', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(4, message='Не съществува модел с толкова кратко име, моля въведи модел с минимум 4 символа')], verbose_name='Модел')),
                ('weight', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(80, message='Не съществува толкова лека макара.Въведи минимум 80гр.'), django.core.validators.MaxValueValidator(500, message='Не съществува толкова тежка макара.Въведи максимум до 500гр.')], verbose_name='Тегло (гр.)')),
                ('bearings', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(15, message='Макарата не може да има повече от 15 лагера')], verbose_name='Лагери')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(20, message='Няма такава макара която струва по-малко от 20 лв.'), django.core.validators.MaxValueValidator(2500, message='Няма такава макара която струва повече от 2500 лв.')], verbose_name='Цена')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Снимка URL')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
